# User Service Configuration
server:
  port: 8085

spring:
  application:
    name: user-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: fleet_user
    password: fleet_password_2024
    driver-class-name: org.postgresql.Driver

  # JPA Configuration - SCHEMA MANAGED BY FLYWAY
  jpa:
    hibernate:
      ddl-auto: validate  # Only validate, never create/update schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # Flyway Configuration - MANAGES DATABASE SCHEMA
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true  # Prevent accidental data loss

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: "fleet_redis_2024"
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thaquidheen@gmail.com
    password: 9656  # Consider using environment variables for security
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ====== MISSING CONFIGURATIONS TO ADD ======

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      company-service:
        connectTimeout: 3000
        readTimeout: 5000
        # Retry configuration
        retryer:
          period: 1000
          maxPeriod: 5000
          maxAttempts: 3

# Resilience4j Circuit Breaker (for Feign)
resilience4j:
  circuitbreaker:
    instances:
      company-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10



# ================================================

# JWT Configuration
jwt:
  secret: fleet-management-secret-key-for-jwt-token-signing-should-be-very-long-and-secure-and-is-at-least-64-bytes
  expiration: 86400000
  refresh-expiration: 604800000
  issuer: fleet-management-system
  audience: fleet-management-users

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway
  endpoint:
    health:
      enabled: true
      show-details: always
    flyway:
      enabled: true

# Logging Configuration
logging:
  level:
    com.fleetmanagement.userservice: DEBUG
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG
    com.fleetmanagement.userservice.client: DEBUG  # For Feign client debugging

app:
  name: Fleet Management User Service
  version: 1.0.0
  description: User authentication and authorization service

  # Security Configuration
  security:
    max-failed-attempts: 5
    account-lock-duration: 30  # minutes
    password-reset-token-validity: 1  # hour
    email-verification-token-validity: 24  # hours

  # Session Configuration
  session:
    max-concurrent-sessions: 3
    session-timeout: 30  # minutes

  # Rate Limiting
  rate-limit:
    login-attempts: 5
    time-window: 900  # 15 minutes in seconds

  # Email Configuration
  email:
    verification:
      enabled: true
      expiration: 3600000
      base-url: http://localhost:3000
    from:
      name: "Fleet Management System"
      address: "noreply@fleetmanagement.com"

  # ====== NEW CONFIGURATIONS ======

  # Company Service Integration
  company:
    service:
      url: http://company-service  # Service discovery will resolve this
      timeout: 5000
      retry-attempts: 3
    validation:
      cache-duration: 300  # 5 minutes

  # Subscription Limits (fallback values)
  subscription:
    limits:
      basic:
        max-users: 5
        max-vehicles: 10
      premium:
        max-users: 50
        max-vehicles: 100
      enterprise:
        max-users: 1000
        max-vehicles: 10000
      owner:
        max-users: -1  # Unlimited
        max-vehicles: -1  # Unlimited