-- V3__Create_users_table.sql
-- Create main users table with all fields

CREATE TABLE users (
                       id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                       username VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       first_name VARCHAR(50) NOT NULL,
                       last_name VARCHAR(50) NOT NULL,
                       phone_number VARCHAR(20),
                       role user_role NOT NULL DEFAULT 'VIEWER',
                       status user_status NOT NULL DEFAULT 'ACTIVE',
                       company_id UUID,
                       email_verified BOOLEAN DEFAULT FALSE,
                       phone_verified BOOLEAN DEFAULT FALSE,
                       employee_id VARCHAR(50),
                       department VARCHAR(100),
                       failed_login_attempts INTEGER DEFAULT 0,
                       last_failed_login_at TIMESTAMP,
                       last_login_at TIMESTAMP,
                       last_login TIMESTAMP,
                       last_login_ip VARCHAR(45),
                       password_changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       last_password_change TIMESTAMP,
                       force_password_change BOOLEAN DEFAULT FALSE,
                       account_locked_until TIMESTAMP,
                       timezone VARCHAR(10) DEFAULT 'UTC',
                       language VARCHAR(10) DEFAULT 'en',
                       profile_picture_url VARCHAR(255),
                       profile_image_url VARCHAR(255),
                       notes TEXT,
                       email_verification_token VARCHAR(255),
                       email_verification_expiry TIMESTAMP,
                       password_reset_token VARCHAR(255),
                       password_reset_expiry TIMESTAMP,
                       two_factor_enabled BOOLEAN DEFAULT FALSE,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       created_by UUID,
                       updated_by UUID,
                       version BIGINT DEFAULT 0
);