# ===============================
# PROMETHEUS ALERT RULES
# File: monitoring/alert-rules.yml
# ===============================
groups:
  - name: fleet_management_alerts
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is above 512MB for {{ $labels.job }}"

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage is above 80% for {{ $labels.job }}"

      # Database Alerts
      - alert: DatabaseConnectionHigh
        expr: hikaricp_connections_active > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections on {{ $labels.job }}"
          description: "Active database connections are above 80 for {{ $labels.job }}"

      - alert: SlowDatabaseQueries
        expr: rate(hikaricp_connections_timeout_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database query timeouts on {{ $labels.job }}"
          description: "Database queries are timing out on {{ $labels.job }}"

      # Kafka Alerts
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag_sum > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Kafka consumer lag"
          description: "Kafka consumer lag is above 1000 messages"

      # Fleet-specific Business Alerts
      - alert: HighDeviceOfflineRate
        expr: (fleet_devices_offline / fleet_devices_total) * 100 > 20
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High device offline rate"
          description: "More than 20% of devices are offline"

      - alert: LocationDataDelay
        expr: (time() - fleet_last_location_update) > 300
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Location data processing delay"
          description: "Location data hasn't been processed for more than 5 minutes"

      - alert: AlertProcessingDelay
        expr: fleet_alert_processing_duration_seconds > 60
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Alert processing is slow"
          description: "Alert processing is taking more than 60 seconds"